# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from pathlib import Path

# 変数
base_url = "https://192.168.56.105"
base_save_folder = "screenshots/"
base_download_dir = "downloads/"
test_account_mail = "contributor@weko-selenium.jp"
test_account_password = "uspass123"
guest_mail = "guest@weko-selenium.jp"

system_administrator = 'wekosoftware@nii.ac.jp'
system_administrator_password = 'uspass123'
repository_administrator = 'repoadmin@example.org'
repository_administrator_password = 'uspass123'
community_administrator = 'comadmin@example.org'
community_administrator_password = 'uspass123'
contributor = 'contributor@example.org'
contributor_password = 'uspass123'
general = 'user@example.org'
general_password = 'uspass123'
term_title = 'Test Terms and Conditions Title'
edited_term_title = 'Edited ' + term_title

class SetupDriver:
    def setup_driver(self):
        options = webdriver.ChromeOptions()
        
        dldir_path = Path(base_download_dir)
        dldir_path.mkdir(exist_ok=True)
        download_dir = str(dldir_path.resolve())
        # print(download_dir)


        options.add_experimental_option("prefs", {
            "download.default_directory": download_dir,
            "plugins.always_open_pdf_externally": True
        })

        self.driver = webdriver.Remote(
            command_executor="http://selenium:4444/wd/hub", options=options
        )
        self.vars = {}

        self.driver.implicitly_wait(10)
        
        self.driver.get(base_url)
        self.driver.find_element(By.XPATH,"/html/body/div/div[2]/button[3]").click()
        self.driver.find_element(By.XPATH,"/html/body/div/div[3]/p[2]/a").click()

    def teardown_method(self):
        self.driver.quit()
