version: '3'

services:
  selenium:               # selenium container
    image: selenium/standalone-chrome:latest # docker hubのselenium公式イメージ
    shm_size: 1gb         # ホストとメモリを共有するために設定
    volumes:
      - ./work:/work
    ports:
      - 4444:4444         # selenium sever port
      - 7900:7900         # 実行中のChromeを確認するVNC用port
    restart: always       # コンテナが落ちたら自動で再起動
  
  python:                 # python container
    build: ./py_context   # python3のbuild contextを指定
    volumes: 
      - ./work:/work      # ローカルの"./work"とコンテナの"/work"をバインド
    tty: true             # ターミナル入力を受け付ける
    depends_on:           # seleniumコンテナの後で起動させるように指定
      - selenium
    restart: always       # コンテナが落ちたら自動で再起動